# Generated by Django 4.1.7 on 2023-03-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lessonprogress",
            old_name="profile",
            new_name="user",
        ),
    ]
